
import __ASTRO_IMAGE_IMPORT_ZnSqp4 from "../../../assets/etl.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Fetl.md";
import __ASTRO_IMAGE_IMPORT_ZsLIa from "../../../assets/peek.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Finstallation.md";
import __ASTRO_IMAGE_IMPORT_Z1vtgRl from "../../../assets/inspector-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_Z1CKxqU from "../../../assets/inspector-visual.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_yJ5mP from "../../../assets/interactive.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Freference%2Finteractive.md";
import __ASTRO_IMAGE_IMPORT_1sIzAW from "../../../assets/inspector-llm.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_1INT6c from "../../../assets/inspector-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_p89Aq from "../../../assets/inspector-visual.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_8pg6K from "../../../assets/praxis-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Fpraxis.md";
import __ASTRO_IMAGE_IMPORT_1a2c1E from "../../../assets/praxis-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Fpraxis.md";
export default new Map([["../../../assets/etl.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Fetl.md", __ASTRO_IMAGE_IMPORT_ZnSqp4], ["../../../assets/peek.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Finstallation.md", __ASTRO_IMAGE_IMPORT_ZsLIa], ["../../../assets/inspector-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md", __ASTRO_IMAGE_IMPORT_Z1vtgRl], ["../../../assets/inspector-visual.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md", __ASTRO_IMAGE_IMPORT_Z1CKxqU], ["../../../assets/interactive.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Freference%2Finteractive.md", __ASTRO_IMAGE_IMPORT_yJ5mP], ["../../../assets/inspector-llm.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Finspector.md", __ASTRO_IMAGE_IMPORT_1sIzAW], ["../../../assets/inspector-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Finspector.md", __ASTRO_IMAGE_IMPORT_1INT6c], ["../../../assets/inspector-visual.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Finspector.md", __ASTRO_IMAGE_IMPORT_p89Aq], ["../../../assets/praxis-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Fpraxis.md", __ASTRO_IMAGE_IMPORT_8pg6K], ["../../../assets/praxis-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fui%2Fpraxis.md", __ASTRO_IMAGE_IMPORT_1a2c1E]]);
		