
import __ASTRO_IMAGE_IMPORT_ZsLIa from "../../../assets/peek.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Finstallation.md";
import __ASTRO_IMAGE_IMPORT_ZnSqp4 from "../../../assets/etl.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Fetl.md";
import __ASTRO_IMAGE_IMPORT_Z1pBrFs from "../../../assets/chat.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Fchat.md";
import __ASTRO_IMAGE_IMPORT_1iF8f0 from "../../../assets/example-rest-async.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md";
import __ASTRO_IMAGE_IMPORT_GqnH from "../../../assets/example-rest-async.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md";
import __ASTRO_IMAGE_IMPORT_Z1fRxUE from "../../../assets/example-async-progress.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md";
import __ASTRO_IMAGE_IMPORT_2wkS1Y from "../../../assets/example-async-progress.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md";
import __ASTRO_IMAGE_IMPORT_Z1vtgRl from "../../../assets/inspector-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_Z1CKxqU from "../../../assets/inspector-visual.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md";
import __ASTRO_IMAGE_IMPORT_yJ5mP from "../../../assets/interactive.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Freference%2Finteractive.md";
import __ASTRO_IMAGE_IMPORT_Z2f2bmj from "../../../assets/praxis-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fworkflows%2Fpraxis.md";
import __ASTRO_IMAGE_IMPORT_Z1jrSd2 from "../../../assets/praxis-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fworkflows%2Fpraxis.md";
export default new Map([["../../../assets/peek.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting-started%2Finstallation.md", __ASTRO_IMAGE_IMPORT_ZsLIa], ["../../../assets/etl.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Fetl.md", __ASTRO_IMAGE_IMPORT_ZnSqp4], ["../../../assets/chat.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Fchat.md", __ASTRO_IMAGE_IMPORT_Z1pBrFs], ["../../../assets/example-rest-async.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md", __ASTRO_IMAGE_IMPORT_1iF8f0], ["../../../assets/example-rest-async.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md", __ASTRO_IMAGE_IMPORT_GqnH], ["../../../assets/example-async-progress.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md", __ASTRO_IMAGE_IMPORT_Z1fRxUE], ["../../../assets/example-async-progress.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fexamples%2Frest-api.md", __ASTRO_IMAGE_IMPORT_2wkS1Y], ["../../../assets/inspector-overview.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md", __ASTRO_IMAGE_IMPORT_Z1vtgRl], ["../../../assets/inspector-visual.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Finternals%2Finspector.md", __ASTRO_IMAGE_IMPORT_Z1CKxqU], ["../../../assets/interactive.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Freference%2Finteractive.md", __ASTRO_IMAGE_IMPORT_yJ5mP], ["../../../assets/praxis-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fworkflows%2Fpraxis.md", __ASTRO_IMAGE_IMPORT_Z2f2bmj], ["../../../assets/praxis-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fworkflows%2Fpraxis.md", __ASTRO_IMAGE_IMPORT_Z1jrSd2]]);
		